### ISSUE TITLE
Windows overapping with Taskbar

### ISSUE THREAD

**Issue by jonathan-reichardt** [glsorre/amethystwindows#13]
**Describe the bug**
When the Taskbar isn't located at the bottom of the screen, but at the top or sides, then Amethyst positions the windows so that they're overlapping with the taskbar, while ther's an empty space at the bottom of the screen.

**To Reproduce**
1. Move the Taskbar from the Bottom to the Top or Sides
2. Force the Windows to be reevaluated `mod1 + Z`

**Screenshots**
![image](https://user-images.githubusercontent.com/31374296/105698287-fc760400-5f05-11eb-966d-460459504e26.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 20H2 Build 19042.746

**Comment by garciaErick** [comment]
+1 to this, I think this is due to Amethyst windows only taking in account if the taskbar is at the bottom. I would propose 2 solutions, have settings to have custom paddings, meaning I can choose each side and each padding separately. You could also just get the taskbar position and height programatically and have it all seamlessly.

**Comment by hlorand** [comment]
When I place the task bar to the right side of the screen it works perfectly, does not overlap. Only overlaps when the taskbar is in the left or top.

**Comment by glsorre** [comment]
Hi all! This will be solved with #19.
I will keep you posted.

**Comment by glsorre** [comment]
Hi the problem is solved. Going to release asap.
