### ISSUE TITLE
Application Crash on Start - .NET Unhandled XamlParseException Event ID 1026/1000/1001

### ISSUE THREAD

**Issue by Stobz** [glsorre/amethystwindows#74]
I have been testing out your software for a few days now. Thank you, it looks very promising and I am interested in using it in a project I am working on.

Today Amethyst would not load. I have included the short list of recently installed items that have recently been installed.
OS: Windows 10 version 21H2 build 19044.1566
![AmethystWindows Crash v2 0 4 1a 2022-03-05](https://user-images.githubusercontent.com/100380056/156907150-da284b55-a393-44ce-a66a-7ef98da52809.jpg)

The Windows Application Event Log shows EventID 1026, 1000, 1001 each time the app attempts to start. I have attached the event logs from 2.0.4.1a failing to start with the  .NET Unhandled XamlParseException.

[AmethystWindows Crash v2.0.4.1a 2022-03-05.txt](https://github.com/glsorre/amethystwindows/files/8191863/AmethystWindows.Crash.v2.0.4.1a.2022-03-05.txt)

Amethyst continues to not load even after uninstalling the two C++ redistributables that were recently installed, rebooting, and uninstalling/reinstalling Amethyst. I tried to two versions v2.0.3.1a and v2.0.4.1a, and both x64 and x86 of v2.0.4.1a.

**Comment by glsorre** [comment]
@Stobz0 It is definitely something with your saved settings...could you paste `%APPDATA%/Amethyst Windows/MySetting.json`?

**Comment by Stobz0** [comment]
Thank you for the information, you were correct and it is now working again.
In C:\Users\<user>\AppData\Local\AmethystWindows\MySettings.json  the problem was that the old DesktopID was no longer valid. Deleting the MySettings.json resolved the problem for a quick fix. After restarting the app, it successfully reproduced a new MySettings.json file and functioned properly.  I narrowed it down to this being the breaking part:

Broken Json- {"DesktopMonitors":[{"DesktopID":"fc4471a8-7c1b-4270-b390-2154023efec6",
Working Json- {"DesktopMonitors":[{"DesktopID":"663a8918-7f0d-4fb3-9238-88b06d3466d5",

I use two monitors with two different desktop scaling. However, I could not reproduce this issue by swapping between different combinations of monitors and video connections on my graphics card.

**Comment by Stobz0** [comment]
Later today. I rebooted a few times, and the DesktopID of my system changed again and the app would crash on load. I was able to get it to start loading again normally by deleting/renaming the json file. Below is the most recent json.
[MySettings.json.txt](https://github.com/glsorre/amethystwindows/files/8194325/MySettings.json.txt)

**Comment by glsorre** [comment]
Thank you @Stobz0 ! I am working on a fix.

**Comment by MBombeck** [comment]
Same bug here

**Comment by joshua-pgatour** [comment]
I'm having the bug too
